### ISSUE TITLE
where to run the command?

### ISSUE THREAD

**Issue by oren** [jmptable/rm-dl-annotated#11]
I just wanted to make sure i understand the usage of this tool. is this command running on my laptop? 
rm-dl-annotated.sh "/Super Cool Research Paper I Scribbled All Over"

**Comment by jmpinit** [comment]
Yes, that's right. It interacts with your tablet via the reMarkable web API.

**Comment by oren** [comment]
Does it mean that I need to create an account with RM?

**Comment by jmpinit** [comment]
Yes, that's correct.

**Comment by oren** [comment]
got it. i don't use it to i guess this library can't help me. sorry for troubling you.
