### ISSUE TITLE
Not working for "reMarkable .lines file, version=3"

### ISSUE THREAD

**Issue by franky-li** [jmptable/rm-dl-annotated#4]
this tools seems not working for "reMarkable .lines file, version=3 ", would you please check?

**Comment by fharper** [comment]
I think you are right. I'm a new reMarkable owner, so not sure how it was working before, but from the code, it seems like they had `.lines` files, but now they are `.rm` ones in the UUID folder.

**Comment by fharper** [comment]
[rM2svg](https://github.com/reHackable/maxio/blob/master/tools/rM2svg) will also [have to be updated](https://github.com/reHackable/maxio/issues/27).

**Comment by jmpinit** [comment]
Hello, sorry this took so long to fix! Almost exactly a year... Anyway, the tool should work with the new  `.rm` files now. Happy holidays.
