### ISSUE TITLE
Install Instructions missing

### ISSUE THREAD

**Issue by webboty** [jmptable/rm-dl-annotated#6]
Thanks for your work on such RM enhancements. I was thinking about using it but there are no install instructions. Can you please add a couple paragraphs that points users in the right direction? Would be great. Thanks in advance.

**Comment by jmpinit** [comment]
Thanks for the feedback. I've added a bit more direction in the readme in dc375b261a7099ae3a98ef575899fb9bf45d9954. It would be handy to have more info on what the roadblocks are for people trying to install this. I'd be happy to improve it further. Closing for now.
