### ISSUE TITLE
Not working with .lines version 5

### ISSUE THREAD

**Issue by davidswarbrick** [jmptable/rm-dl-annotated#7]
Similar to #4, the tool exits with an error:
```
Not a valid reMarkable file: <header=b'reMarkable .lines file, version=5          '> <nlayers=1
```
Posting here, however this may be an issue with upstream, apologies if so.
Tested on reMarkable 1 version 2.0.2.0
rmapi 0.0.9
rm2svg 0.0.2

**Comment by jmpinit** [comment]
Thanks for the report. I believe this is fixed with rM2svg version 0.0.2.1. I've updated the link in the readme to use a fork by delaere that has some other improvements that support new tools added in recent versions.
